title: Portal Fisika As-Syifa
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gigihpamungkas.github.io/semuatentangfisika

aux_links:
  Template Repository: 

# Di dalam file _config.yml
markdown: kramdown
kramdown:
  math_engine: mathjax

# Tambahkan ini di bagian paling bawah
aux_links:
  "MathJax Script":
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
    # Di dalam file _config.yml
footer_content: "Â© 2026 Semua Tentang Fisika | Portal Fisika Assyifa Boarding School"